version: "3.8"

services:
 db:
   image: postgres 
   environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"

   volumes:
     - ./tmp/db:/var/lib/postgresql/data
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/timecalender
   ports:
     - 8000:8000
   depends_on:
     - db

volumes:
  postgres_data: