# Generated by Django 3.2.13 on 2022-06-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeSlots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_time", models.CharField(max_length=100)),
                ("to", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=100)),
            ],
        ),
    ]
